# Independently managed Cloud Run image used behind Firebase Hosting.
# Build production images with cloudbuild.yaml so public client configuration is
# present during `next build`.

FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_SUPABASE_URL
ARG PAWTNER_ENV
ARG NEXT_PUBLIC_PAWTNER_ENV
ARG PAWTNER_STAGING_SUPABASE_PROJECT_REF
ARG PAWTNER_COMMIT_SHA
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ARG NEXT_PUBLIC_FIREBASE_OBSERVABILITY_ENABLED
ARG NEXT_PUBLIC_FEATURE_FIREBASE_AUTH_ENABLED
ARG FEATURE_FIREBASE_AUTH_ENABLED
ARG FEATURE_GOVERNMENT_PETS_ENABLED
ARG FEATURE_CLOSED_PILOT_ADOPTION_OPERATIONS_ENABLED
ARG NEXT_PUBLIC_FEATURE_CLOSED_PILOT_ADOPTION_OPERATIONS_ENABLED

ENV PAWTNER_ENV=$PAWTNER_ENV \
    NEXT_PUBLIC_PAWTNER_ENV=$NEXT_PUBLIC_PAWTNER_ENV \
    PAWTNER_STAGING_SUPABASE_PROJECT_REF=$PAWTNER_STAGING_SUPABASE_PROJECT_REF \
    PAWTNER_COMMIT_SHA=$PAWTNER_COMMIT_SHA \
    NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL \
    NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY \
    NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY \
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN \
    NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID \
    NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID \
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID \
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET \
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID \
    NEXT_PUBLIC_FIREBASE_OBSERVABILITY_ENABLED=$NEXT_PUBLIC_FIREBASE_OBSERVABILITY_ENABLED \
    NEXT_PUBLIC_FEATURE_FIREBASE_AUTH_ENABLED=$NEXT_PUBLIC_FEATURE_FIREBASE_AUTH_ENABLED \
    FEATURE_FIREBASE_AUTH_ENABLED=$FEATURE_FIREBASE_AUTH_ENABLED \
    FEATURE_GOVERNMENT_PETS_ENABLED=$FEATURE_GOVERNMENT_PETS_ENABLED \
    FEATURE_CLOSED_PILOT_ADOPTION_OPERATIONS_ENABLED=$FEATURE_CLOSED_PILOT_ADOPTION_OPERATIONS_ENABLED \
    NEXT_PUBLIC_FEATURE_CLOSED_PILOT_ADOPTION_OPERATIONS_ENABLED=$NEXT_PUBLIC_FEATURE_CLOSED_PILOT_ADOPTION_OPERATIONS_ENABLED

ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=8080
ENV HOSTNAME=0.0.0.0

RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

USER nextjs
EXPOSE 8080
CMD ["node", "server.js"]
